from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

from backlog_py.core.models import BacklogProject
from backlog_py.core.repository import TaskRecord
from backlog_py.security.paths import assert_path_within_base


BOARD_START = "<!-- BOARD_START -->"
BOARD_END = "<!-- BOARD_END -->"


def export_board_to_file(
    project: BacklogProject,
    tasks: Sequence[TaskRecord],
    output_file: str | None = None,
) -> Path:
    """Write a Backlog.md-style board export under the project root."""
    target = _safe_project_output_path(project, output_file or "Backlog.md")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        generate_board_markdown(tasks, project.config.statuses or [], project.config.project_name),
        encoding="utf-8",
    )
    return target


def update_readme_with_board(
    project: BacklogProject,
    tasks: Sequence[TaskRecord],
    *,
    version: str | None = None,
) -> Path:
    """Insert or replace the marked board section in README.md."""
    readme_path = _safe_project_output_path(project, "README.md")
    existing = readme_path.read_text(encoding="utf-8") if readme_path.exists() else ""
    full_board = generate_board_markdown(tasks, project.config.statuses or [], project.config.project_name)
    timestamp = _timestamp_from_board(full_board)
    board_table = _board_table_from_export(full_board)
    version_text = f" ({version})" if version else ""
    section = (
        f"## 📊 {project.config.project_name} Project Status{version_text}\n\n"
        "This board was automatically generated by [Backlog.md](https://backlog.md)\n\n"
        f"Generated on: {timestamp}\n\n"
        f"{board_table}"
    )

    start = existing.find(BOARD_START)
    end = existing.find(BOARD_END)
    license_index = existing.find("## License")
    if start != -1 and end != -1 and start < end:
        before = existing[: start + len(BOARD_START)]
        after = existing[end:]
        updated = f"{before}\n\n{section}\n\n{after}"
    elif license_index != -1:
        before = existing[:license_index]
        after = existing[license_index:]
        updated = f"{before}{BOARD_START}\n\n{section}\n\n{BOARD_END}\n\n{after}"
    else:
        prefix = existing.rstrip()
        updated = f"{prefix}\n\n{BOARD_START}\n\n{section}\n\n{BOARD_END}\n" if prefix else f"{BOARD_START}\n\n{section}\n\n{BOARD_END}\n"

    readme_path.write_text(updated, encoding="utf-8")
    return readme_path


def generate_board_markdown(tasks: Sequence[TaskRecord], statuses: Sequence[str], project_name: str) -> str:
    """Return a markdown table board export compatible with upstream Backlog.md."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    ordered_statuses, grouped = _status_groups(tasks, statuses)
    header = (
        "# Kanban Board Export (powered by Backlog.md)\n"
        f"Generated on: {timestamp}\n"
        f"Project: {project_name}\n\n"
    )
    if not ordered_statuses:
        return f"{header}No tasks found."

    table_header = f"| {' | '.join(status or 'No Status' for status in ordered_statuses)} |"
    separator = f"| {' | '.join('---' for _ in ordered_statuses)} |"
    columns = [_ordered_column(grouped[status], tasks) for status in ordered_statuses]
    max_rows = max((len(column) for column in columns), default=0)
    rows = [table_header, separator]
    for row_index in range(max_rows):
        cells = [_format_task_cell(column[row_index]) if row_index < len(column) else "" for column in columns]
        rows.append(f"| {' | '.join(cells)} |")

    if max_rows == 0:
        return f"{header}{chr(10).join(rows)}\n\nNo tasks found.\n"
    return f"{header}{chr(10).join(rows)}\n"


def _safe_project_output_path(project: BacklogProject, output_file: str) -> Path:
    raw_path = Path(output_file)
    target = raw_path if raw_path.is_absolute() else project.root / raw_path
    return assert_path_within_base(project.root, target)


def _timestamp_from_board(board: str) -> str:
    for line in board.splitlines():
        if line.startswith("Generated on: "):
            return line.removeprefix("Generated on: ")
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")


def _board_table_from_export(board: str) -> str:
    lines = board.splitlines()
    start = next((index for index, line in enumerate(lines) if line.startswith("| ")), len(lines))
    return "\n".join(lines[start:]).strip()


def _status_groups(
    tasks: Sequence[TaskRecord],
    statuses: Sequence[str],
) -> tuple[list[str], dict[str, list[TaskRecord]]]:
    canonical: dict[str, str] = {}
    ordered_statuses: list[str] = []
    grouped: dict[str, list[TaskRecord]] = {}
    for status in statuses:
        trimmed = str(status).strip()
        if not trimmed:
            continue
        canonical.setdefault(trimmed.casefold(), trimmed)
        if trimmed not in grouped:
            ordered_statuses.append(trimmed)
            grouped[trimmed] = []

    for task in tasks:
        raw_status = task.status.strip()
        if not raw_status:
            continue
        status = canonical.get(raw_status.casefold(), raw_status)
        if status not in grouped:
            ordered_statuses.append(status)
            grouped[status] = []
        grouped[status].append(task)

    return ordered_statuses, grouped


def _ordered_column(status_tasks: Sequence[TaskRecord], all_tasks: Sequence[TaskRecord]) -> list[TaskRecord]:
    by_id = {_task_key(task.id): task for task in all_tasks}
    top_level: list[TaskRecord] = []
    children: dict[str, list[TaskRecord]] = {}
    for task in sorted(status_tasks, key=_board_sort_key):
        parent_id = _frontmatter_string(task, "parent_task_id")
        parent = by_id.get(_task_key(parent_id)) if parent_id else None
        if parent is not None and parent.status == task.status:
            children.setdefault(_task_key(parent.id), []).append(task)
        else:
            top_level.append(task)

    ordered: list[TaskRecord] = []
    for task in top_level:
        ordered.append(task)
        ordered.extend(sorted(children.get(_task_key(task.id), []), key=lambda child: _task_sort_key(child.id)))
    return ordered


def _board_sort_key(task: TaskRecord) -> tuple[float, tuple[str, tuple[tuple[int, int | str], ...]]]:
    return (-_task_timestamp(task), _task_sort_key(task.id))


def _task_timestamp(task: TaskRecord) -> float:
    raw_date = _frontmatter_string(task, "updated_date") or _frontmatter_string(task, "created_date")
    if not raw_date:
        return 0
    try:
        return datetime.fromisoformat(raw_date).timestamp()
    except ValueError:
        return 0


def _format_task_cell(task: TaskRecord) -> str:
    prefix = "└─ " if _frontmatter_string(task, "parent_task_id") else ""
    assignees = _frontmatter_list(task, "assignee")
    labels = _frontmatter_list(task, "labels")
    assignees_text = f" [{', '.join(_at_prefixed(assignee) for assignee in assignees)}]" if assignees else ""
    labels_text = f"<br>*{' '.join(f'#{label}' for label in labels)}*" if labels else ""
    return f"{prefix}**{task.id.upper()}** - {task.title}{assignees_text}{labels_text}"


def _frontmatter_string(task: TaskRecord, key: str) -> str:
    value = task.parsed.frontmatter.get(key)
    return "" if value is None else str(value).strip()


def _frontmatter_list(task: TaskRecord, key: str) -> list[str]:
    value = task.parsed.frontmatter.get(key)
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return [item.strip() for item in str(value).split(",") if item.strip()]


def _at_prefixed(value: str) -> str:
    return value if value.startswith("@") else f"@{value}"


def _task_key(task_id: str) -> str:
    return task_id.strip().casefold()


def _task_sort_key(task_id: str) -> tuple[str, tuple[tuple[int, int | str], ...]]:
    prefix, _, suffix = task_id.partition("-")
    return prefix.casefold(), tuple(_sort_segment(segment) for segment in suffix.replace(".", "-").split("-"))


def _sort_segment(segment: str) -> tuple[int, int | str]:
    if segment.isdigit():
        return 0, int(segment)
    return 1, segment.casefold()
